### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by 1v9** [HighwayStar/android_device_nubia_nx569j#2]
I tried to modify the lineage-15.1 device tree to build Dirty Unicorns o8x, but obviously there are a lot of compatibility issues such as missing SHARED_LIBRARY.  
I am a newbie and I will be very grateful for your answer.

```
device/nubia/nx569j/camera/QCamera2/Android.mk: error: camera.msm8952 (SHARED_LIBRARIES android-arm) missing libqdMetaData (SHARED_LIBRARIES android-arm) 

device/nubia/nx569j/camera/QCamera2/Android.mk: error: camera.msm8952 (SHARED_LIBRARIES android-arm) missing libqservice (SHARED_LIBRARIES android-arm) 

frameworks/av/services/audiopolicy/Android.mk: error: libaudiopolicyservice (SHARED_LIBRARIES android-arm64) missing libaudiopolicymanager (SHARED_LIBRARIES android-arm64) 

frameworks/av/services/audiopolicy/Android.mk: error: libaudiopolicyservice (SHARED_LIBRARIES android-arm) missing libaudiopolicymanager (SHARED_LIBRARIES android-arm) 

hardware/qcom/media/msm8974/mm-video-v4l2/vidc/vdec.mk: error: libOmxVdec (SHARED_LIBRARIES android-arm64) missing libqdMetaData (SHARED_LIBRARIES android-arm64) 

hardware/qcom/media/msm8974/mm-video-v4l2/vidc/vdec.mk: error: libOmxVdec (SHARED_LIBRARIES android-arm) missing libqdMetaData (SHARED_LIBRARIES android-arm) 
```

**Comment by HighwayStar** [comment]
It looks like your build system using wrong HAL includes, for example hardware/qcom/media/msm8974/mm-video-v4l2/vidc/vdec.mk   while it should use includes from msm8952 dir. Check other qcom devices trees for qcom specific flags, maybe you have to set something to point HAL paths to 8952 branches.

**Comment by 1v9** [comment]
> It looks like your build system using wrong HAL includes, for example hardware/qcom/media/msm8974/mm-video-v4l2/vidc/vdec.mk while it should use includes from msm8952 dir. Check other qcom devices trees for qcom specific flags, maybe you have to set something to point HAL paths to 8952 branches.

👍 Thanks for your answer, I will try.

**Comment by jashasweejena** [comment]
I was having issue with a similar error. Can you please help me with examples of some flags or something which can help?
